/**
 * Permission Keys - Centralized definition of all permissions in the system
 * Format: RESOURCE_ACTION
 */

export const PERMISSIONS = {
  // Guest permissions (public access)
  PRODUCT_VIEW: "product:view",
  PRODUCT_SEARCH: "product:search",
  PRODUCT_BROWSE: "product:browse",
  SHOP_VIEW: "shop:view",
  REVIEW_VIEW: "review:view",
  PLATFORM_CATALOG_VIEW: "platform:view",

  // Customer permissions
  PROFILE_VIEW: "profile:view",
  PROFILE_UPDATE: "profile:update",
  CART_VIEW: "cart:view",
  CART_ADD: "cart:add",
  CART_UPDATE: "cart:update",
  CART_REMOVE: "cart:remove",
  ORDER_CREATE: "order:create",
  ORDER_VIEW: "order:view",
  ORDER_CANCEL: "order:cancel",
  ORDER_TRACK: "order:track",
  PAYMENT_INITIATE: "payment:initiate",
  PAYMENT_CONFIRM: "payment:confirm",
  WALLET_VIEW: "wallet:view",
  WALLET_TOPUP: "wallet:topup",
  WALLET_TRANSACTION_VIEW: "wallet:transaction:view",
  TICKET_CREATE: "ticket:create",
  TICKET_VIEW: "ticket:view",
  TICKET_UPDATE: "ticket:update",
  TICKET_CLOSE: "ticket:close",
  TICKET_VIEW_ALL: "ticket:view:all", // Staff view all tickets
  TICKET_ASSIGN: "ticket:assign", // Assign ticket to staff
  TICKET_ESCALATE: "ticket:escalate", // Escalate ticket priority
  REVIEW_CREATE: "review:create",
  REVIEW_UPDATE: "review:update",
  REVIEW_DELETE: "review:delete",
  REPORT_CREATE: "report:create",
  CONVERSATION_VIEW: "conversation:view",
  CONVERSATION_CREATE: "conversation:create",
  CONVERSATION_MESSAGE: "conversation:message",
  CONVERSATION_INTERNAL_NOTE: "conversation:internal_note", // Staff internal notes
  CONVERSATION_VIEW_ALL: "conversation:view:all", // Staff view all conversations
  REFUND_REQUEST: "refund:request",

  // Seller permissions
  SHOP_CREATE: "shop:create",
  SHOP_UPDATE: "shop:update",
  SHOP_VIEW_OWN: "shop:view:own",
  PRODUCT_CREATE: "product:create",
  PRODUCT_UPDATE: "product:update",
  PRODUCT_DELETE: "product:delete",
  PRODUCT_VIEW_OWN: "product:view:own",
  INVENTORY_VIEW: "inventory:view",
  INVENTORY_ADD: "inventory:add",
  INVENTORY_UPDATE: "inventory:update",
  INVENTORY_DELETE: "inventory:delete",
  ORDER_VIEW_OWN: "order:view:own",
  ORDER_PROCESS: "order:process",
  ORDER_DELIVER: "order:deliver",
  ORDER_UPDATE_STATUS: "order:update:status",
  SALES_REPORT_VIEW: "sales:report:view",
  SHOP_ANALYTICS_VIEW: "shop:analytics:view",
  PAYOUT_REQUEST: "payout:request",
  PAYOUT_VIEW: "payout:view",
  CONVERSATION_SELLER_VIEW: "conversation:seller:view",
  CONVERSATION_SELLER_MESSAGE: "conversation:seller:message",
  REVIEW_REPLY: "review:reply",

  // Moderator permissions
  REVIEW_MODERATE: "review:moderate",
  REVIEW_HIDE: "review:hide",
  REVIEW_DELETE_MODERATOR: "review:delete:moderator",
  COMMENT_MODERATE: "comment:moderate",
  COMMENT_HIDE: "comment:hide",
  COMMENT_DELETE: "comment:delete",
  REPORT_VIEW: "report:view",
  REPORT_REVIEW: "report:review",
  REPORT_RESOLVE: "report:resolve",
  REPORT_REJECT: "report:reject",
  SHOP_SUSPEND: "shop:suspend",
  SHOP_UNSUSPEND: "shop:unsuspend",
  USER_RESTRICT: "user:restrict",
  USER_UNRESTRICT: "user:unrestrict",
  CONTENT_MODERATE: "content:moderate",

  // Complaint Moderation permissions (NEW)
  // Seller complaint permissions
  COMPLAINT_VIEW_SHOP: "complaint:view:shop", // Seller view shop complaints
  COMPLAINT_RESPOND: "complaint:respond", // Seller respond to complaints
  COMPLAINT_PROPOSE_RESOLUTION: "complaint:propose", // Seller propose resolution

  // Customer complaint permissions
  COMPLAINT_ESCALATE: "complaint:escalate", // Customer escalate to moderator
  COMPLAINT_APPEAL: "complaint:appeal", // Customer/Seller file appeal

  // Moderator complaint permissions
  COMPLAINT_QUEUE_VIEW: "complaint:queue:view", // View complaint queue
  COMPLAINT_ASSIGN: "complaint:assign", // Assign complaints
  COMPLAINT_DECISION: "complaint:decision", // Make decisions
  COMPLAINT_INTERNAL_NOTE: "complaint:internal_note", // Add internal notes
  COMPLAINT_REQUEST_INFO: "complaint:request_info", // Request more info

  // Admin/Senior Mod complaint permissions
  COMPLAINT_APPEAL_REVIEW: "complaint:appeal:review", // Review appeals
  COMPLAINT_PENALTY_ISSUE: "complaint:penalty:issue", // Issue seller penalties
  COMPLAINT_STATS_VIEW: "complaint:stats:view", // View moderator stats
  COMPLAINT_CONFIG: "complaint:config", // Configure escalation rules
  COMPLAINT_TEMPLATE_MANAGE: "complaint:template:manage", // Manage decision templates

  // Admin permissions
  USER_VIEW: "user:view",
  USER_CREATE: "user:create",
  USER_UPDATE: "user:update",
  USER_DELETE: "user:delete",
  USER_LOCK: "user:lock",
  USER_UNLOCK: "user:unlock",
  USER_BAN: "user:ban",
  USER_UNBAN: "user:unban",
  ROLE_VIEW: "role:view",
  ROLE_CREATE: "role:create",
  ROLE_UPDATE: "role:update",
  ROLE_DELETE: "role:delete",
  PERMISSION_VIEW: "permission:view",
  PERMISSION_ASSIGN: "permission:assign",
  PERMISSION_REVOKE: "permission:revoke",
  CATEGORY_VIEW: "category:view",
  CATEGORY_CREATE: "category:create",
  CATEGORY_UPDATE: "category:update",
  CATEGORY_DELETE: "category:delete",
  PLATFORM_CATALOG_MANAGE: "platform:manage",
  SELLER_APPROVE: "seller:approve",
  SELLER_REJECT: "seller:reject",
  SELLER_VIEW_APPLICATIONS: "seller:view:applications",
  POLICY_VIEW: "policy:view",
  POLICY_UPDATE: "policy:update",
  SYSTEM_CONFIG_VIEW: "system:config:view",
  SYSTEM_CONFIG_UPDATE: "system:config:update",
  AI_SYSTEM_MANAGE: "ai:system:manage",
  AUDIT_LOG_VIEW: "audit:log:view",
  ORDER_VIEW_ALL: "order:view:all",
  ORDER_MANAGE: "order:manage",
  WALLET_VIEW_ALL: "wallet:view:all",
  WALLET_ADJUST: "wallet:adjust",
  PAYOUT_APPROVE: "payout:approve",
  PAYOUT_REJECT: "payout:reject",
  PAYOUT_VIEW_ALL: "payout:view:all",
  REFUND_APPROVE: "refund:approve",
  REFUND_REJECT: "refund:reject",
  REFUND_VIEW_ALL: "refund:view:all",
  ANALYTICS_VIEW: "analytics:view",
  SYSTEM_MONITOR: "system:monitor",
} as const;

/**
 * Permission definitions with metadata
 */
export const PERMISSION_DEFINITIONS = [
  // Guest permissions
  {
    permissionKey: PERMISSIONS.PRODUCT_VIEW,
    permissionName: "View Product",
    description: "View product details",
    resource: "product",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.PRODUCT_SEARCH,
    permissionName: "Search Products",
    description: "Search and filter products",
    resource: "product",
    action: "search",
  },
  {
    permissionKey: PERMISSIONS.PRODUCT_BROWSE,
    permissionName: "Browse Products",
    description: "Browse product catalog",
    resource: "product",
    action: "browse",
  },
  {
    permissionKey: PERMISSIONS.SHOP_VIEW,
    permissionName: "View Shop",
    description: "View shop details",
    resource: "shop",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.REVIEW_VIEW,
    permissionName: "View Reviews",
    description: "View product reviews",
    resource: "review",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.PLATFORM_CATALOG_VIEW,
    permissionName: "View Platform Catalog",
    description: "View available platforms",
    resource: "platform",
    action: "view",
  },

  // Customer permissions
  {
    permissionKey: PERMISSIONS.PROFILE_VIEW,
    permissionName: "View Profile",
    description: "View own profile",
    resource: "profile",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.PROFILE_UPDATE,
    permissionName: "Update Profile",
    description: "Update own profile information",
    resource: "profile",
    action: "update",
  },
  {
    permissionKey: PERMISSIONS.CART_VIEW,
    permissionName: "View Cart",
    description: "View shopping cart",
    resource: "cart",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.CART_ADD,
    permissionName: "Add to Cart",
    description: "Add products to cart",
    resource: "cart",
    action: "add",
  },
  {
    permissionKey: PERMISSIONS.CART_UPDATE,
    permissionName: "Update Cart",
    description: "Update cart items",
    resource: "cart",
    action: "update",
  },
  {
    permissionKey: PERMISSIONS.CART_REMOVE,
    permissionName: "Remove from Cart",
    description: "Remove items from cart",
    resource: "cart",
    action: "remove",
  },
  {
    permissionKey: PERMISSIONS.ORDER_CREATE,
    permissionName: "Create Order",
    description: "Create new order",
    resource: "order",
    action: "create",
  },
  {
    permissionKey: PERMISSIONS.ORDER_VIEW,
    permissionName: "View Orders",
    description: "View own orders",
    resource: "order",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.ORDER_CANCEL,
    permissionName: "Cancel Order",
    description: "Cancel own order",
    resource: "order",
    action: "cancel",
  },
  {
    permissionKey: PERMISSIONS.ORDER_TRACK,
    permissionName: "Track Order",
    description: "Track order status",
    resource: "order",
    action: "track",
  },
  {
    permissionKey: PERMISSIONS.PAYMENT_INITIATE,
    permissionName: "Initiate Payment",
    description: "Initiate payment for order",
    resource: "payment",
    action: "initiate",
  },
  {
    permissionKey: PERMISSIONS.PAYMENT_CONFIRM,
    permissionName: "Confirm Payment",
    description: "Confirm payment completion",
    resource: "payment",
    action: "confirm",
  },
  {
    permissionKey: PERMISSIONS.WALLET_VIEW,
    permissionName: "View Wallet",
    description: "View own wallet balance",
    resource: "wallet",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.WALLET_TOPUP,
    permissionName: "Top Up Wallet",
    description: "Add funds to wallet",
    resource: "wallet",
    action: "topup",
  },
  {
    permissionKey: PERMISSIONS.WALLET_TRANSACTION_VIEW,
    permissionName: "View Wallet Transactions",
    description: "View wallet transaction history",
    resource: "wallet",
    action: "transaction:view",
  },
  {
    permissionKey: PERMISSIONS.TICKET_CREATE,
    permissionName: "Create Support Ticket",
    description: "Create support ticket",
    resource: "ticket",
    action: "create",
  },
  {
    permissionKey: PERMISSIONS.TICKET_VIEW,
    permissionName: "View Support Tickets",
    description: "View own support tickets",
    resource: "ticket",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.TICKET_UPDATE,
    permissionName: "Update Support Ticket",
    description: "Update own support ticket",
    resource: "ticket",
    action: "update",
  },
  {
    permissionKey: PERMISSIONS.TICKET_CLOSE,
    permissionName: "Close Support Ticket",
    description: "Close own support ticket",
    resource: "ticket",
    action: "close",
  },
  {
    permissionKey: PERMISSIONS.TICKET_VIEW_ALL,
    permissionName: "View All Tickets",
    description: "View all support tickets (staff)",
    resource: "ticket",
    action: "view:all",
  },
  {
    permissionKey: PERMISSIONS.TICKET_ASSIGN,
    permissionName: "Assign Ticket",
    description: "Assign ticket to staff member",
    resource: "ticket",
    action: "assign",
  },
  {
    permissionKey: PERMISSIONS.TICKET_ESCALATE,
    permissionName: "Escalate Ticket",
    description: "Escalate ticket priority",
    resource: "ticket",
    action: "escalate",
  },
  {
    permissionKey: PERMISSIONS.REVIEW_CREATE,
    permissionName: "Create Review",
    description: "Create product review",
    resource: "review",
    action: "create",
  },
  {
    permissionKey: PERMISSIONS.REVIEW_UPDATE,
    permissionName: "Update Review",
    description: "Update own review",
    resource: "review",
    action: "update",
  },
  {
    permissionKey: PERMISSIONS.REVIEW_DELETE,
    permissionName: "Delete Review",
    description: "Delete own review",
    resource: "review",
    action: "delete",
  },
  {
    permissionKey: PERMISSIONS.REPORT_CREATE,
    permissionName: "Create Report",
    description: "Report product, shop, or user",
    resource: "report",
    action: "create",
  },
  {
    permissionKey: PERMISSIONS.CONVERSATION_VIEW,
    permissionName: "View Conversations",
    description: "View conversations",
    resource: "conversation",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.CONVERSATION_CREATE,
    permissionName: "Create Conversation",
    description: "Create new conversation",
    resource: "conversation",
    action: "create",
  },
  {
    permissionKey: PERMISSIONS.CONVERSATION_MESSAGE,
    permissionName: "Send Message",
    description: "Send message in conversation",
    resource: "conversation",
    action: "message",
  },
  {
    permissionKey: PERMISSIONS.CONVERSATION_INTERNAL_NOTE,
    permissionName: "Add Internal Note",
    description: "Add internal staff note to conversation",
    resource: "conversation",
    action: "internal_note",
  },
  {
    permissionKey: PERMISSIONS.CONVERSATION_VIEW_ALL,
    permissionName: "View All Conversations",
    description: "View all conversations (staff)",
    resource: "conversation",
    action: "view:all",
  },
  {
    permissionKey: PERMISSIONS.REFUND_REQUEST,
    permissionName: "Request Refund",
    description: "Request refund for order",
    resource: "refund",
    action: "request",
  },

  // Seller permissions
  {
    permissionKey: PERMISSIONS.SHOP_CREATE,
    permissionName: "Create Shop",
    description: "Create new shop",
    resource: "shop",
    action: "create",
  },
  {
    permissionKey: PERMISSIONS.SHOP_UPDATE,
    permissionName: "Update Shop",
    description: "Update own shop",
    resource: "shop",
    action: "update",
  },
  {
    permissionKey: PERMISSIONS.SHOP_VIEW_OWN,
    permissionName: "View Own Shop",
    description: "View own shop details",
    resource: "shop",
    action: "view:own",
  },
  {
    permissionKey: PERMISSIONS.PRODUCT_CREATE,
    permissionName: "Create Product",
    description: "Create new product listing",
    resource: "product",
    action: "create",
  },
  {
    permissionKey: PERMISSIONS.PRODUCT_UPDATE,
    permissionName: "Update Product",
    description: "Update own product",
    resource: "product",
    action: "update",
  },
  {
    permissionKey: PERMISSIONS.PRODUCT_DELETE,
    permissionName: "Delete Product",
    description: "Delete own product",
    resource: "product",
    action: "delete",
  },
  {
    permissionKey: PERMISSIONS.PRODUCT_VIEW_OWN,
    permissionName: "View Own Products",
    description: "View own product listings",
    resource: "product",
    action: "view:own",
  },
  {
    permissionKey: PERMISSIONS.INVENTORY_VIEW,
    permissionName: "View Inventory",
    description: "View inventory items",
    resource: "inventory",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.INVENTORY_ADD,
    permissionName: "Add Inventory",
    description: "Add inventory items",
    resource: "inventory",
    action: "add",
  },
  {
    permissionKey: PERMISSIONS.INVENTORY_UPDATE,
    permissionName: "Update Inventory",
    description: "Update inventory items",
    resource: "inventory",
    action: "update",
  },
  {
    permissionKey: PERMISSIONS.INVENTORY_DELETE,
    permissionName: "Delete Inventory",
    description: "Delete inventory items",
    resource: "inventory",
    action: "delete",
  },
  {
    permissionKey: PERMISSIONS.ORDER_VIEW_OWN,
    permissionName: "View Own Orders",
    description: "View orders for own shop",
    resource: "order",
    action: "view:own",
  },
  {
    permissionKey: PERMISSIONS.ORDER_PROCESS,
    permissionName: "Process Order",
    description: "Process order",
    resource: "order",
    action: "process",
  },
  {
    permissionKey: PERMISSIONS.ORDER_DELIVER,
    permissionName: "Deliver Order",
    description: "Deliver order items",
    resource: "order",
    action: "deliver",
  },
  {
    permissionKey: PERMISSIONS.ORDER_UPDATE_STATUS,
    permissionName: "Update Order Status",
    description: "Update order status",
    resource: "order",
    action: "update:status",
  },
  {
    permissionKey: PERMISSIONS.SALES_REPORT_VIEW,
    permissionName: "View Sales Report",
    description: "View sales reports",
    resource: "sales",
    action: "report:view",
  },
  {
    permissionKey: PERMISSIONS.SHOP_ANALYTICS_VIEW,
    permissionName: "View Shop Analytics",
    description: "View shop analytics",
    resource: "shop",
    action: "analytics:view",
  },
  {
    permissionKey: PERMISSIONS.PAYOUT_REQUEST,
    permissionName: "Request Payout",
    description: "Request payout",
    resource: "payout",
    action: "request",
  },
  {
    permissionKey: PERMISSIONS.PAYOUT_VIEW,
    permissionName: "View Payouts",
    description: "View payout history",
    resource: "payout",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.CONVERSATION_SELLER_VIEW,
    permissionName: "View Seller Conversations",
    description: "View conversations as seller",
    resource: "conversation",
    action: "seller:view",
  },
  {
    permissionKey: PERMISSIONS.CONVERSATION_SELLER_MESSAGE,
    permissionName: "Send Seller Message",
    description: "Send message as seller",
    resource: "conversation",
    action: "seller:message",
  },
  {
    permissionKey: PERMISSIONS.REVIEW_REPLY,
    permissionName: "Reply to Review",
    description: "Reply to customer reviews as shop owner",
    resource: "review",
    action: "reply",
  },

  // Moderator permissions
  {
    permissionKey: PERMISSIONS.REVIEW_MODERATE,
    permissionName: "Moderate Review",
    description: "Moderate reviews",
    resource: "review",
    action: "moderate",
  },
  {
    permissionKey: PERMISSIONS.REVIEW_HIDE,
    permissionName: "Hide Review",
    description: "Hide review",
    resource: "review",
    action: "hide",
  },
  {
    permissionKey: PERMISSIONS.REVIEW_DELETE_MODERATOR,
    permissionName: "Delete Review (Moderator)",
    description: "Delete review as moderator",
    resource: "review",
    action: "delete:moderator",
  },
  {
    permissionKey: PERMISSIONS.COMMENT_MODERATE,
    permissionName: "Moderate Comment",
    description: "Moderate comments",
    resource: "comment",
    action: "moderate",
  },
  {
    permissionKey: PERMISSIONS.COMMENT_HIDE,
    permissionName: "Hide Comment",
    description: "Hide comment",
    resource: "comment",
    action: "hide",
  },
  {
    permissionKey: PERMISSIONS.COMMENT_DELETE,
    permissionName: "Delete Comment",
    description: "Delete comment",
    resource: "comment",
    action: "delete",
  },
  {
    permissionKey: PERMISSIONS.REPORT_VIEW,
    permissionName: "View Reports",
    description: "View all reports",
    resource: "report",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.REPORT_REVIEW,
    permissionName: "Review Report",
    description: "Review reported content",
    resource: "report",
    action: "review",
  },
  {
    permissionKey: PERMISSIONS.REPORT_RESOLVE,
    permissionName: "Resolve Report",
    description: "Resolve report",
    resource: "report",
    action: "resolve",
  },
  {
    permissionKey: PERMISSIONS.REPORT_REJECT,
    permissionName: "Reject Report",
    description: "Reject report",
    resource: "report",
    action: "reject",
  },
  {
    permissionKey: PERMISSIONS.SHOP_SUSPEND,
    permissionName: "Suspend Shop",
    description: "Suspend shop",
    resource: "shop",
    action: "suspend",
  },
  {
    permissionKey: PERMISSIONS.SHOP_UNSUSPEND,
    permissionName: "Unsuspend Shop",
    description: "Unsuspend shop",
    resource: "shop",
    action: "unsuspend",
  },
  {
    permissionKey: PERMISSIONS.USER_RESTRICT,
    permissionName: "Restrict User",
    description: "Restrict user access",
    resource: "user",
    action: "restrict",
  },
  {
    permissionKey: PERMISSIONS.USER_UNRESTRICT,
    permissionName: "Unrestrict User",
    description: "Remove user restrictions",
    resource: "user",
    action: "unrestrict",
  },
  {
    permissionKey: PERMISSIONS.CONTENT_MODERATE,
    permissionName: "Moderate Content",
    description: "Moderate any content",
    resource: "content",
    action: "moderate",
  },

  // Admin permissions
  {
    permissionKey: PERMISSIONS.USER_VIEW,
    permissionName: "View Users",
    description: "View all users",
    resource: "user",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.USER_CREATE,
    permissionName: "Create User",
    description: "Create new user",
    resource: "user",
    action: "create",
  },
  {
    permissionKey: PERMISSIONS.USER_UPDATE,
    permissionName: "Update User",
    description: "Update user information",
    resource: "user",
    action: "update",
  },
  {
    permissionKey: PERMISSIONS.USER_DELETE,
    permissionName: "Delete User",
    description: "Delete user",
    resource: "user",
    action: "delete",
  },
  {
    permissionKey: PERMISSIONS.USER_LOCK,
    permissionName: "Lock User",
    description: "Lock user account",
    resource: "user",
    action: "lock",
  },
  {
    permissionKey: PERMISSIONS.USER_UNLOCK,
    permissionName: "Unlock User",
    description: "Unlock user account",
    resource: "user",
    action: "unlock",
  },
  {
    permissionKey: PERMISSIONS.USER_BAN,
    permissionName: "Ban User",
    description: "Ban user account",
    resource: "user",
    action: "ban",
  },
  {
    permissionKey: PERMISSIONS.USER_UNBAN,
    permissionName: "Unban User",
    description: "Unban user account",
    resource: "user",
    action: "unban",
  },
  {
    permissionKey: PERMISSIONS.ROLE_VIEW,
    permissionName: "View Roles",
    description: "View all roles",
    resource: "role",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.ROLE_CREATE,
    permissionName: "Create Role",
    description: "Create new role",
    resource: "role",
    action: "create",
  },
  {
    permissionKey: PERMISSIONS.ROLE_UPDATE,
    permissionName: "Update Role",
    description: "Update role",
    resource: "role",
    action: "update",
  },
  {
    permissionKey: PERMISSIONS.ROLE_DELETE,
    permissionName: "Delete Role",
    description: "Delete role",
    resource: "role",
    action: "delete",
  },
  {
    permissionKey: PERMISSIONS.PERMISSION_VIEW,
    permissionName: "View Permissions",
    description: "View all permissions",
    resource: "permission",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.PERMISSION_ASSIGN,
    permissionName: "Assign Permission",
    description: "Assign permission to role",
    resource: "permission",
    action: "assign",
  },
  {
    permissionKey: PERMISSIONS.PERMISSION_REVOKE,
    permissionName: "Revoke Permission",
    description: "Revoke permission from role",
    resource: "permission",
    action: "revoke",
  },
  {
    permissionKey: PERMISSIONS.CATEGORY_VIEW,
    permissionName: "View Categories",
    description: "View all categories",
    resource: "category",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.CATEGORY_CREATE,
    permissionName: "Create Category",
    description: "Create new category",
    resource: "category",
    action: "create",
  },
  {
    permissionKey: PERMISSIONS.CATEGORY_UPDATE,
    permissionName: "Update Category",
    description: "Update category",
    resource: "category",
    action: "update",
  },
  {
    permissionKey: PERMISSIONS.CATEGORY_DELETE,
    permissionName: "Delete Category",
    description: "Delete category",
    resource: "category",
    action: "delete",
  },
  {
    permissionKey: PERMISSIONS.PLATFORM_CATALOG_MANAGE,
    permissionName: "Manage Platform Catalog",
    description: "Manage platform catalog",
    resource: "platform",
    action: "manage",
  },
  {
    permissionKey: PERMISSIONS.SELLER_APPROVE,
    permissionName: "Approve Seller",
    description: "Approve seller registration",
    resource: "seller",
    action: "approve",
  },
  {
    permissionKey: PERMISSIONS.SELLER_REJECT,
    permissionName: "Reject Seller",
    description: "Reject seller registration",
    resource: "seller",
    action: "reject",
  },
  {
    permissionKey: PERMISSIONS.SELLER_VIEW_APPLICATIONS,
    permissionName: "View Seller Applications",
    description: "View seller applications",
    resource: "seller",
    action: "view:applications",
  },
  {
    permissionKey: PERMISSIONS.POLICY_VIEW,
    permissionName: "View Policies",
    description: "View system policies",
    resource: "policy",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.POLICY_UPDATE,
    permissionName: "Update Policies",
    description: "Update system policies",
    resource: "policy",
    
    action: "update",
  },
  {
    permissionKey: PERMISSIONS.SYSTEM_CONFIG_VIEW,
    permissionName: "View System Config",
    description: "View system configuration",
    resource: "system",
    action: "config:view",
  },
  {
    permissionKey: PERMISSIONS.SYSTEM_CONFIG_UPDATE,
    permissionName: "Update System Config",
    description: "Update system configuration",
    resource: "system",
    action: "config:update",
  },
  {
    permissionKey: PERMISSIONS.AI_SYSTEM_MANAGE,
    permissionName: "Manage AI System",
    description: "Manage AI system",
    resource: "ai",
    action: "system:manage",
  },
  {
    permissionKey: PERMISSIONS.AUDIT_LOG_VIEW,
    permissionName: "View Audit Logs",
    description: "View audit logs",
    resource: "audit",
    action: "log:view",
  },
  {
    permissionKey: PERMISSIONS.ORDER_VIEW_ALL,
    permissionName: "View All Orders",
    description: "View all orders",
    resource: "order",
    action: "view:all",
  },
  {
    permissionKey: PERMISSIONS.ORDER_MANAGE,
    permissionName: "Manage Orders",
    description: "Manage all orders",
    resource: "order",
    action: "manage",
  },
  {
    permissionKey: PERMISSIONS.WALLET_VIEW_ALL,
    permissionName: "View All Wallets",
    description: "View all wallets",
    resource: "wallet",
    action: "view:all",
  },
  {
    permissionKey: PERMISSIONS.WALLET_ADJUST,
    permissionName: "Adjust Wallet",
    description: "Adjust wallet balance",
    resource: "wallet",
    action: "adjust",
  },
  {
    permissionKey: PERMISSIONS.PAYOUT_APPROVE,
    permissionName: "Approve Payout",
    description: "Approve payout request",
    resource: "payout",
    action: "approve",
  },
  {
    permissionKey: PERMISSIONS.PAYOUT_REJECT,
    permissionName: "Reject Payout",
    description: "Reject payout request",
    resource: "payout",
    action: "reject",
  },
  {
    permissionKey: PERMISSIONS.PAYOUT_VIEW_ALL,
    permissionName: "View All Payouts",
    description: "View all payouts",
    resource: "payout",
    action: "view:all",
  },
  {
    permissionKey: PERMISSIONS.REFUND_APPROVE,
    permissionName: "Approve Refund",
    description: "Approve refund request",
    resource: "refund",
    action: "approve",
  },
  {
    permissionKey: PERMISSIONS.REFUND_REJECT,
    permissionName: "Reject Refund",
    description: "Reject refund request",
    resource: "refund",
    action: "reject",
  },
  {
    permissionKey: PERMISSIONS.REFUND_VIEW_ALL,
    permissionName: "View All Refunds",
    description: "View all refunds",
    resource: "refund",
    action: "view:all",
  },
  {
    permissionKey: PERMISSIONS.ANALYTICS_VIEW,
    permissionName: "View Analytics",
    description: "View system analytics",
    resource: "analytics",
    action: "view",
  },
  {
    permissionKey: PERMISSIONS.SYSTEM_MONITOR,
    permissionName: "Monitor System",
    description: "Monitor system operations",
    resource: "system",
    action: "monitor",
  },

  // Complaint Moderation permissions
  {
    permissionKey: PERMISSIONS.COMPLAINT_VIEW_SHOP,
    permissionName: "View Shop Complaints",
    description: "View complaints for own shop",
    resource: "complaint",
    action: "view:shop",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_RESPOND,
    permissionName: "Respond to Complaint",
    description: "Respond to customer complaints",
    resource: "complaint",
    action: "respond",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_PROPOSE_RESOLUTION,
    permissionName: "Propose Resolution",
    description: "Propose resolution for complaints",
    resource: "complaint",
    action: "propose",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_ESCALATE,
    permissionName: "Escalate Complaint",
    description: "Escalate complaint to moderator",
    resource: "complaint",
    action: "escalate",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_APPEAL,
    permissionName: "Appeal Decision",
    description: "Appeal moderator decision",
    resource: "complaint",
    action: "appeal",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_QUEUE_VIEW,
    permissionName: "View Complaint Queue",
    description: "View complaint moderation queue",
    resource: "complaint",
    action: "queue:view",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_ASSIGN,
    permissionName: "Assign Complaint",
    description: "Assign complaints to moderators",
    resource: "complaint",
    action: "assign",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_DECISION,
    permissionName: "Make Decision",
    description: "Make decision on complaints",
    resource: "complaint",
    action: "decision",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_INTERNAL_NOTE,
    permissionName: "Add Internal Note",
    description: "Add internal notes to complaints",
    resource: "complaint",
    action: "internal_note",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_REQUEST_INFO,
    permissionName: "Request Information",
    description: "Request more information from parties",
    resource: "complaint",
    action: "request_info",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_APPEAL_REVIEW,
    permissionName: "Review Appeal",
    description: "Review and decide on appeals",
    resource: "complaint",
    action: "appeal:review",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_PENALTY_ISSUE,
    permissionName: "Issue Penalty",
    description: "Issue penalties to sellers",
    resource: "complaint",
    action: "penalty:issue",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_STATS_VIEW,
    permissionName: "View Complaint Stats",
    description: "View moderator statistics",
    resource: "complaint",
    action: "stats:view",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_CONFIG,
    permissionName: "Configure Complaints",
    description: "Configure complaint escalation rules",
    resource: "complaint",
    action: "config",
  },
  {
    permissionKey: PERMISSIONS.COMPLAINT_TEMPLATE_MANAGE,
    permissionName: "Manage Templates",
    description: "Manage decision templates",
    resource: "complaint",
    action: "template:manage",
  },
] as const;

/**
 * Role-Permission mappings
 */
export const ROLE_PERMISSIONS = {
  CUSTOMER: [
    // Profile
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,
    // Shop - Allow customer to register as seller
    PERMISSIONS.SHOP_CREATE,
    PERMISSIONS.SHOP_VIEW_OWN,
    // Product - Allow viewing own products while waiting for shop approval
    PERMISSIONS.PRODUCT_VIEW_OWN,
    // Cart
    PERMISSIONS.CART_VIEW,
    PERMISSIONS.CART_ADD,
    PERMISSIONS.CART_UPDATE,
    PERMISSIONS.CART_REMOVE,
    // Order
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CANCEL,
    PERMISSIONS.ORDER_TRACK,
    // Payment
    PERMISSIONS.PAYMENT_INITIATE,
    PERMISSIONS.PAYMENT_CONFIRM,
    // Wallet
    PERMISSIONS.WALLET_VIEW,
    PERMISSIONS.WALLET_TOPUP,
    PERMISSIONS.WALLET_TRANSACTION_VIEW,
    // Support
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_CLOSE,
    // Review
    PERMISSIONS.REVIEW_CREATE,
    PERMISSIONS.REVIEW_UPDATE,
    PERMISSIONS.REVIEW_DELETE,
    // Report
    PERMISSIONS.REPORT_CREATE,
    // Conversation
    PERMISSIONS.CONVERSATION_VIEW,
    PERMISSIONS.CONVERSATION_CREATE,
    PERMISSIONS.CONVERSATION_MESSAGE,
    // Refund
    PERMISSIONS.REFUND_REQUEST,
    // Complaint (Customer)
    PERMISSIONS.COMPLAINT_ESCALATE,
    PERMISSIONS.COMPLAINT_APPEAL,
    // Public
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_SEARCH,
    PERMISSIONS.PRODUCT_BROWSE,
    PERMISSIONS.SHOP_VIEW,
    PERMISSIONS.REVIEW_VIEW,
    PERMISSIONS.PLATFORM_CATALOG_VIEW,
  ],

  // SELLER = CUSTOMER permissions + seller permissions
  SELLER: [
    // CUSTOMER permissions (keep buyer features)
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.SHOP_CREATE,
    PERMISSIONS.SHOP_VIEW_OWN,
    PERMISSIONS.PRODUCT_VIEW_OWN,
    PERMISSIONS.CART_VIEW,
    PERMISSIONS.CART_ADD,
    PERMISSIONS.CART_UPDATE,
    PERMISSIONS.CART_REMOVE,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CANCEL,
    PERMISSIONS.ORDER_TRACK,
    PERMISSIONS.PAYMENT_INITIATE,
    PERMISSIONS.PAYMENT_CONFIRM,
    PERMISSIONS.WALLET_VIEW,
    PERMISSIONS.WALLET_TOPUP,
    PERMISSIONS.WALLET_TRANSACTION_VIEW,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_CLOSE,
    PERMISSIONS.REVIEW_CREATE,
    PERMISSIONS.REVIEW_UPDATE,
    PERMISSIONS.REVIEW_DELETE,
    PERMISSIONS.REPORT_CREATE,
    PERMISSIONS.CONVERSATION_VIEW,
    PERMISSIONS.CONVERSATION_CREATE,
    PERMISSIONS.CONVERSATION_MESSAGE,
    PERMISSIONS.REFUND_REQUEST,

    // SELLER additional permissions
    PERMISSIONS.SHOP_UPDATE,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADD,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_DELETE,
    PERMISSIONS.ORDER_VIEW_OWN,
    PERMISSIONS.ORDER_PROCESS,
    PERMISSIONS.ORDER_DELIVER,
    PERMISSIONS.ORDER_UPDATE_STATUS,
    PERMISSIONS.SALES_REPORT_VIEW,
    PERMISSIONS.SHOP_ANALYTICS_VIEW,
    PERMISSIONS.PAYOUT_REQUEST,
    PERMISSIONS.PAYOUT_VIEW,
    PERMISSIONS.CONVERSATION_SELLER_VIEW,
    PERMISSIONS.CONVERSATION_SELLER_MESSAGE,
    PERMISSIONS.REVIEW_REPLY,

    // Complaint (Seller)
    PERMISSIONS.COMPLAINT_VIEW_SHOP,
    PERMISSIONS.COMPLAINT_RESPOND,
    PERMISSIONS.COMPLAINT_PROPOSE_RESOLUTION,
    PERMISSIONS.COMPLAINT_APPEAL,

    // Public
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_SEARCH,
    PERMISSIONS.PRODUCT_BROWSE,
    PERMISSIONS.SHOP_VIEW,
    PERMISSIONS.REVIEW_VIEW,
    PERMISSIONS.PLATFORM_CATALOG_VIEW,
  ],

  MODERATOR: [
    // Support ticket handling
    PERMISSIONS.TICKET_VIEW_ALL,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.TICKET_ESCALATE,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_CLOSE,
    // Conversation handling
    PERMISSIONS.CONVERSATION_VIEW_ALL,
    PERMISSIONS.CONVERSATION_MESSAGE,
    PERMISSIONS.CONVERSATION_INTERNAL_NOTE,
    // Product moderation
    // Review moderation
    PERMISSIONS.REVIEW_MODERATE,
    PERMISSIONS.REVIEW_HIDE,
    PERMISSIONS.REVIEW_DELETE_MODERATOR,
    // Comment moderation
    PERMISSIONS.COMMENT_MODERATE,
    PERMISSIONS.COMMENT_HIDE,
    PERMISSIONS.COMMENT_DELETE,
    // Report handling
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_REVIEW,
    PERMISSIONS.REPORT_RESOLVE,
    PERMISSIONS.REPORT_REJECT,
    // Shop management
    PERMISSIONS.SHOP_SUSPEND,
    PERMISSIONS.SHOP_UNSUSPEND,
    // Seller application management
    PERMISSIONS.SELLER_VIEW_APPLICATIONS,
    PERMISSIONS.SELLER_APPROVE,
    PERMISSIONS.SELLER_REJECT,
    // User restrictions
    PERMISSIONS.USER_RESTRICT,
    PERMISSIONS.USER_UNRESTRICT,
    // General
    PERMISSIONS.CONTENT_MODERATE,
    // Complaint Moderation
    PERMISSIONS.COMPLAINT_QUEUE_VIEW,
    PERMISSIONS.COMPLAINT_ASSIGN,
    PERMISSIONS.COMPLAINT_DECISION,
    PERMISSIONS.COMPLAINT_INTERNAL_NOTE,
    PERMISSIONS.COMPLAINT_REQUEST_INFO,
    PERMISSIONS.COMPLAINT_PENALTY_ISSUE,
    PERMISSIONS.COMPLAINT_STATS_VIEW,
    // Public
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_SEARCH,
    PERMISSIONS.PRODUCT_BROWSE,
    PERMISSIONS.SHOP_VIEW,
    PERMISSIONS.REVIEW_VIEW,
    PERMISSIONS.PLATFORM_CATALOG_VIEW,
  ],
  ADMIN: [
    // All permissions
    ...Object.values(PERMISSIONS),
  ],
} as const;
